### ISSUE TITLE
BibTeX citation

### ISSUE THREAD

**Issue by rickwierenga** [fastai/imagenette#16]
Is there a preferred BibTeX citation for Imagenette, Imagewoof and Imagewang?

**Comment by jph00** [comment]
Nothing preferred - just a regular web link BibTeX is fine. Thanks for asking!

**Comment by rickwierenga** [comment]
For future reference, here's what I used:

```
@misc{imagewang,
    author    = "Jeremy Howard",
    title     = "Imagewang",
    url       = "https://github.com/fastai/imagenette/"
}
```
