### ISSUE TITLE
Question regarding the LICENSE

### ISSUE THREAD

**Issue by philipp-eisen** [fastai/imagenette#23]
I have a question regarding the license of this. I see this is redistributed with Apache2.0 - I was wondering were you able to gain the rights for that subset of imagenet to be distributed under Apache2.0 or do the same license terms as per the regular imagenet apply?

**Comment by jph00** [comment]
Same terms as regular imagenet. Apache2.0 is only for any code in this repo (which isn't any, currently).

**Comment by philipp-eisen** [comment]
Thanks for the reply!
