### ISSUE TITLE
ResNet 18 - 92% accuracy

### ISSUE THREAD

**Issue by KeremTurgutlu** [fastai/imagenette#3]
I couldn't decide whether to make a PR but resnet18 baseline gives 92+% top1 accuracy on imagenette with out of the box fastai `get_transform`, `size=160`, `TTA` within `n_epoch=40`.

- `best model epoch: 36`
- `non TTA top1: 91%`
- `TTA top1: 92.2%`

github repo: https://github.com/KeremTurgutlu/imagenette_experiments/blob/master/starter.ipynb

everthing is seeded so that it can be reproduced.

**Comment by hasibzunair** [comment]
@KeremTurgutlu Please do share the results of imagewoof when you try it out!

**Comment by jph00** [comment]
@KeremTurgutlu please do a PR if there isn't a better result. :) No TTA, reporting accuracy at the final epoch.
