### ISSUE TITLE
Leaderboards for 128/192/256 image size but datasets are full/320/160

### ISSUE THREAD

**Issue by bentrevett** [fastai/imagenette#31]
Not sure if this is a typo in the leaderboard or just me not understanding the leaderboard.

The leaderboard shows results for 128/192/256 images, however the datasets available are only available in "full size", shortest side of 320 and shortest side of 160.

Does this mean the leaderboard should be changed to full/320/160? Or the results reported are supposed to be from myself resizing the images to either 128/192/256?

**Comment by fpgaminer** [comment]
You're meant to resize the images.  See this line of the example training code: https://github.com/fastai/fastai2/blob/7558097657954d82e946e410032d34c408b44e09/nbs/examples/train_imagenette.py#L24

You can see that it resizes the inputs to the specified size (128, 192, or 256 depending on how `main` is called).
