### ISSUE TITLE
Accuracy of resnet18 with imagewoof

### ISSUE THREAD

**Issue by MacroMayhem** [fastai/imagenette#32]
Hi, 
I tried training Resnet-18(no-pretraining) with imagewoof, since it was missing from the shared results table. Using 160px I managed to go till 75% accuracy without any bells and whistles. I only used data augmentation(random horiz. flip, random rotation, random cropping). I was wondering if you have a baseline measure against which I can compare my results. The difference appears to be significant from xresnet + modifications.

**Comment by muellerzr** [comment]
You should use one of the sizes that are available in the baselines (128, 192, or 256px). Also, make sure you're using the appropriate epoch range (5, 20, 80, or 200).
