### ISSUE TITLE
89% accuracy. 160px 25 epochs

### ISSUE THREAD

**Issue by jinudaniel** [fastai/imagenette#4]
I was able to create a classifier with a resnet like architecture and was able to achieve an accuracy of 89% with 25 epochs for 160px dataset.
github repo: https://github.com/jinudaniel/imagenette

**Comment by jph00** [comment]
Great! Please do a PR adding your info to the readme - but please use one of the existing # epochs groups there (e.g. 20 epochs)

**Comment by jph00** [comment]
Oh and also pick from the sizes listed there - 160px isn't one of them.
