### ISSUE TITLE
Add Self-Supervised baselines for ImageNette

### ISSUE THREAD

**Issue by IgorSusmelj** [fastai/imagenette#54]
Hi, we just recently released some baseline benchmarks using self-supervised models such as MoCo, SimCLR, BYOL here: https://github.com/lightly-ai/lightly/releases/tag/v1.1.12

We used the 160px version of the dataset.

The code we used for benchmarking is here: https://github.com/lightly-ai/lightly/blob/master/docs/source/getting_started/benchmarks/imagenette_benchmark.py

Could we add the baselines to the readme? I'm sure others would be interested in seeing how well self-supervised models perform.

**Comment by jph00** [comment]
@IgorSusmelj sorry for the very late reply. Feel free to send in a PR.
